import type { PageContent } from "../types";

const UPDATED = "2026-08-23";

const SOURCES = [
  { label: "STPCD 2026 — School Teachers' Pay and Conditions Document (DfE)", url: "https://www.gov.uk/government/publications/school-teachers-pay-and-conditions" },
  { label: "STRB — School Teachers' Review Body reports", url: "https://www.gov.uk/government/organisations/school-teachers-review-body" },
  { label: "NAHT — leadership pay guidance", url: "https://www.naht.org.uk/Advice-Support/Pay-and-conditions" },
  { label: "Teachers' Pensions — member contribution tiers", url: "https://www.teacherspensions.co.uk/members/working-life/paying-in/contribution-tiers.aspx" },
];

const leadershipPillar: PageContent = {
  slug: "leadership-pay-scale",
  isPillar: true,
  hub: "leadership",
  title: "Leadership Pay Scale 2026/27",
  metaTitle: "Leadership Pay Scale 2026/27 — Full L1–L43 Teacher Pay Table",
  metaDescription:
    "The complete leadership pay scale for 2026/27. All 43 spine points for every England region, how individual school ranges work, and which roles sit where.",
  primaryKeyword: "leadership pay scale",
  secondaryKeywords: [
    "leadership pay scales", "leadership scale", "leadership payscale",
    "teachers leadership pay scale", "leadership scale teaching",
    "leadership scale teachers", "teacher leadership pay scale",
    "leadership pay", "leadership scales", "l9 teacher pay scale",
    "l12 leadership scale", "inner london leadership scale",
    "leadership scale inner london", "teacher leadership scale",
    "school leadership pay scale", "teaching leadership pay scale",
    "senior leadership pay scale", "headteacher leadership pay scale",
    "leadership pay scale wales", "leadership pay scale 2026",
    "inner london leadership pay scale", "outer london leadership pay scale",
  ],
  calculator: "pay-scale",
  calculatorPreset: { scale: "leadership" },
  intro:
    "The leadership group pay range is a 43-point spine running from £53,585 to £148,829 outside London. This page gives every point for all four England regions, explains how your school picks the seven points that apply to your job, and shows where heads, deputies and assistant heads actually sit.",
  keyTakeaways: [
    "The leadership spine has 43 points, from £53,585 (L1) to £148,829 (L43) in the rest of England, and £63,708 to £158,862 in inner London.",
    "You are never paid on the whole spine. Your school sets a seven-point individual school range (ISR) for each leadership post, and you progress within that.",
    "A headteacher's range is anchored to the school group size, which is calculated from pupil numbers weighted by key stage.",
    "Deputy and assistant head ranges should not normally overlap the headteacher's ISR.",
    "Individual point values between L1 and L43 are indicative — the STPCD publishes the endpoints and your school's pay policy sets the actual range.",
  ],
  blocks: [
    { kind: "h2", text: "What the leadership pay range actually is" },
    { kind: "p", text: "The leadership group pay range covers every post above classroom teaching: assistant headteachers, deputy headteachers, headteachers and executive heads. It is a single 43-point spine, usually written L1 to L43, and every leadership post in a maintained school is paid somewhere on it." },
    { kind: "p", text: "The critical thing to understand — and the thing most pay guides skip — is that nobody is paid on the full spine. The spine is a national framework. Your governing body carves a seven-point slice out of it for your specific job, and you progress within that slice. That slice is called the individual school range, or ISR." },
    { kind: "p", text: "This is quite different from the [main pay range](/teacher-pay-scale/), where M1 to M6 means the same salary in every school in the country. Two deputy heads in neighbouring schools can be on very different money while doing broadly similar jobs, entirely legitimately." },
    { kind: "callout", tone: "info", title: "Leadership pay is not automatic progression", text: "Unlike the main pay range, where progression is normally annual subject to satisfactory performance, movement up a leadership ISR requires sustained high performance judged against your objectives. Two consecutive years of successful performance is the usual threshold for a point." },

    { kind: "h2", text: "Leadership pay scale 2026/27 — full L1 to L43 table" },
    { kind: "p", text: "These figures reflect the STPCD 2026/27 award of 3.5%, effective from 1 September 2026. The STPCD publishes the L1 and L43 endpoints for each region; the points in between follow an even percentage progression across the spine." },
    { kind: "table", caption: "Leadership group pay spine 2026/27, all England regions", head: ["Point", "Rest of England", "Fringe", "Outer London", "Inner London"], rows: [
      ["L1", "£53,585", "£55,060", "£57,837", "£63,708"],
      ["L2", "£54,904", "£56,392", "£59,193", "£65,109"],
      ["L3", "£56,256", "£57,757", "£60,580", "£66,541"],
      ["L4", "£57,641", "£59,155", "£62,000", "£68,005"],
      ["L5", "£59,060", "£60,586", "£63,453", "£69,500"],
      ["L6", "£60,514", "£62,052", "£64,940", "£71,029"],
      ["L7", "£62,004", "£63,554", "£66,463", "£72,591"],
      ["L8", "£63,531", "£65,091", "£68,020", "£74,188"],
      ["L9", "£65,095", "£66,667", "£69,615", "£75,819"],
      ["L10", "£66,698", "£68,280", "£71,246", "£77,487"],
      ["L11", "£68,340", "£69,932", "£72,916", "£79,191"],
      ["L12", "£70,022", "£71,624", "£74,625", "£80,933"],
      ["L13", "£71,746", "£73,357", "£76,375", "£82,713"],
      ["L14", "£73,513", "£75,132", "£78,165", "£84,532"],
      ["L15", "£75,322", "£76,950", "£79,997", "£86,391"],
      ["L16", "£77,177", "£78,813", "£81,872", "£88,291"],
      ["L17", "£79,077", "£80,720", "£83,791", "£90,233"],
      ["L18", "£81,024", "£82,673", "£85,755", "£92,218"],
      ["L19", "£83,019", "£84,673", "£87,765", "£94,246"],
      ["L20", "£85,063", "£86,722", "£89,822", "£96,319"],
      ["L21", "£87,157", "£88,821", "£91,927", "£98,437"],
      ["L22", "£89,303", "£90,970", "£94,082", "£100,602"],
      ["L23", "£91,502", "£93,171", "£96,287", "£102,815"],
      ["L24", "£93,754", "£95,426", "£98,544", "£105,076"],
      ["L25", "£96,063", "£97,735", "£100,854", "£107,387"],
      ["L26", "£98,428", "£100,100", "£103,218", "£109,749"],
      ["L27", "£100,851", "£102,522", "£105,637", "£112,163"],
      ["L28", "£103,334", "£105,003", "£108,113", "£114,630"],
      ["L29", "£105,878", "£107,544", "£110,647", "£117,151"],
      ["L30", "£108,485", "£110,146", "£113,241", "£119,727"],
      ["L31", "£111,156", "£112,812", "£115,895", "£122,360"],
      ["L32", "£113,892", "£115,542", "£118,611", "£125,052"],
      ["L33", "£116,697", "£118,338", "£121,391", "£127,802"],
      ["L34", "£119,570", "£121,201", "£124,237", "£130,613"],
      ["L35", "£122,513", "£124,134", "£127,149", "£133,486"],
      ["L36", "£125,530", "£127,138", "£130,129", "£136,421"],
      ["L37", "£128,620", "£130,214", "£133,179", "£139,422"],
      ["L38", "£131,787", "£133,365", "£136,301", "£142,488"],
      ["L39", "£135,032", "£136,592", "£139,495", "£145,622"],
      ["L40", "£138,356", "£139,898", "£142,765", "£148,825"],
      ["L41", "£141,763", "£143,283", "£146,111", "£152,098"],
      ["L42", "£145,253", "£146,750", "£149,536", "£155,443"],
      ["L43", "£148,829", "£150,301", "£153,041", "£158,862"],
    ]},
    { kind: "callout", tone: "warn", title: "Read the individual points as indicative", text: "The STPCD sets the statutory minimum (L1) and maximum (L43) for each region. The intermediate points shown here are calculated on an even progression between those endpoints and are intended for planning and comparison. Your school's pay policy and your contract are the authority on your actual salary." },

    { kind: "h2", text: "How individual school ranges (ISRs) work" },
    { kind: "p", text: "When a governing body creates or reviews a leadership post, it must set a pay range for that post. The STPCD requires that range to be seven consecutive points on the leadership spine — no more, no less, other than in limited transitional situations." },
    { kind: "p", text: "So a deputy headteacher post might have an ISR of L12 to L18. In the rest of England for 2026/27 that means a range of roughly £70,022 to £81,024. The postholder starts somewhere in that range on appointment and progresses upwards through it as performance is reviewed." },
    { kind: "h3", text: "How the range gets set" },
    { kind: "p", text: "For a headteacher, the starting point is the school group size, which is a function of pupil numbers weighted by key stage. Governors then consider the specific demands of the role — a school in special measures, a split-site school, or a head with a system-leadership brief may justify a higher range." },
    { kind: "p", text: "For deputies and assistant heads, the range is set with reference to the headteacher's ISR and the relative responsibility of the post. There is far more local discretion here, which is precisely why comparable jobs pay so differently between schools." },
    { kind: "h3", text: "The overlap rule" },
    { kind: "p", text: "The STPCD expects that the pay ranges for deputy and assistant headteachers should not normally overlap with the headteacher's ISR. In practice this creates a clear hierarchy: assistant heads sit lowest, deputies above them, the head above both. Governing bodies can depart from this where there is a good reason, but they need to be able to justify it." },

    { kind: "h2", text: "Where each leadership role typically sits" },
    { kind: "p", text: "There is no statutory mapping of job titles to spine points — that is the whole point of the ISR system. But there are strong patterns across the sector, and knowing them helps you judge whether an advertised range is reasonable." },
    { kind: "table", caption: "Typical leadership spine positions by role (indicative, not statutory)", head: ["Role", "Typical ISR", "Rest of England range"], rows: [
      ["Assistant headteacher (primary)", "L4–L10", "£57,641 – £66,698"],
      ["Assistant headteacher (secondary)", "L6–L14", "£60,514 – £73,513"],
      ["Deputy headteacher (primary)", "L8–L16", "£63,531 – £77,177"],
      ["Deputy headteacher (secondary)", "L12–L20", "£70,022 – £85,063"],
      ["Headteacher (small primary)", "L6–L14", "£60,514 – £73,513"],
      ["Headteacher (large primary)", "L14–L22", "£73,513 – £89,303"],
      ["Headteacher (secondary)", "L21–L31", "£87,157 – £111,156"],
      ["Executive head / MAT leader", "L28–L43", "£103,334 – £148,829"],
    ]},
    { kind: "p", text: "These are observed patterns rather than rules. For a detailed breakdown by school size see the [headteacher salary guide](/head-teacher-salary/), and for the two most common stepping-stone roles see [deputy head pay](/deputy-head-teacher-salary/) and [assistant head pay](/assistant-head-teacher-salary/)." },

    { kind: "h2", text: "Leadership pay compared with the upper pay range" },
    { kind: "p", text: "The most common career question at this stage is whether stepping into leadership is worth it financially. The honest answer is that the first step is often smaller than people expect." },
    { kind: "table", caption: "Top of UPS versus entry to leadership, rest of England 2026/27", head: ["Position", "Salary", "Difference vs U3"], rows: [
      ["U3 (top of upper pay range)", "£52,835", "—"],
      ["L1 (bottom of leadership spine)", "£53,585", "+£750"],
      ["L4", "£57,641", "+£4,806"],
      ["L8", "£63,531", "+£10,696"],
      ["L12", "£70,022", "+£17,187"],
    ]},
    { kind: "p", text: "Moving from U3 to L1 is a gross increase of £750 a year, which after tax and a higher pension tier is worth roughly £30 a month. That is the reality of the bottom of the spine, and it is why very few leadership posts are actually advertised at L1. A teacher at the top of the [upper pay range](/upper-pay-range/) who also holds a TLR 1 may well be earning more than an assistant head on a low ISR." },
    { kind: "callout", tone: "tip", title: "Compare total package, not headline salary", text: "A U3 teacher with a £10,530 TLR 1 earns £63,365 — more than an assistant head on L7. Before accepting a leadership post, work out what you currently earn including allowances and put both figures through the [teacher pay calculator](/teacher-pay-calculator/)." },

    { kind: "h2", text: "London weighting on the leadership scale" },
    { kind: "p", text: "London weighting on the leadership spine works the same way as on the classroom scales: it is baked into a higher spine rather than paid as a separate allowance. The premium is proportionally largest at the bottom of the spine." },
    { kind: "table", caption: "London premium at selected spine points, 2026/27", head: ["Point", "Rest of England", "Inner London", "Premium", "Premium %"], rows: [
      ["L1", "£53,585", "£63,708", "£10,123", "18.9%"],
      ["L9", "£65,095", "£75,819", "£10,724", "16.5%"],
      ["L18", "£81,024", "£92,218", "£11,194", "13.8%"],
      ["L28", "£103,334", "£114,630", "£11,296", "10.9%"],
      ["L43", "£148,829", "£158,862", "£10,033", "6.7%"],
    ]},
    { kind: "p", text: "In cash terms the inner London premium stays fairly flat at around £10,000 to £11,000 across the spine. As a percentage it falls sharply, from nearly 19% at L1 to under 7% at L43. Senior leaders in London therefore see much less relative benefit from weighting than classroom teachers do." },

    { kind: "h2", text: "Pension implications of leadership pay" },
    { kind: "p", text: "Every point you move up the leadership spine increases your [Teachers' Pension](/teacher-pension/) in two ways. You build 1/57th of a larger salary each year, and — because the scheme is career average rather than final salary — those higher-paid years count fully and permanently." },
    { kind: "p", text: "The catch is the contribution tier. Leadership salaries push you into the higher tiers quickly, and the tier jumps are not gradual." },
    { kind: "table", caption: "Pension contribution tier at leadership salaries 2026/27", head: ["Spine point (rest of England)", "Salary", "Tier rate", "Annual contribution"], rows: [
      ["L1", "£53,585", "9.6%", "£5,144"],
      ["L5", "£59,060", "10.2%", "£6,024"],
      ["L12", "£70,022", "10.2%", "£7,142"],
      ["L15", "£75,322", "11.7%", "£8,813"],
      ["L26", "£98,428", "11.7%", "£11,516"],
      ["L28", "£103,334", "12.7%", "£13,123"],
    ]},
    { kind: "p", text: "Note the step between L12 and L15. Crossing £72,534 moves you from the 10.2% tier to 11.7%, so a £5,300 gross rise brings a £1,671 increase in pension contributions. It is still a net gain, but the marginal benefit of that particular step is much smaller than the headline suggests." },

    { kind: "h2", text: "Senior and school leadership pay scale variations" },
    { kind: "p", text: "Searches for a senior leadership pay scale or a school leadership pay scale usually mean the same spine. Senior leadership team posts — assistant heads, deputies, the head and any executive or trust-level roles — are all paid on this single 43-point framework, with the differences coming from where each governing body sets the ISR. There is no separate senior leader scale in England." },
    { kind: "p", text: "Two genuine exceptions are worth knowing. In Wales, leaders in maintained schools follow the IWPRB-negotiated scale, which currently mirrors the STPCD endpoints of £53,585 to £148,829 but is reviewed independently, so future awards can diverge. And in academies, the trust can depart from the spine entirely — many use it as a reference, but some set their own leadership bands, particularly for multi-school executives." },

    { kind: "h2", text: "Common mistakes with leadership pay" },
    { kind: "ul", items: [
      "**Assuming L-points mean the same everywhere.** They are national spine values, but which points apply to your job is a local decision.",
      "**Comparing your L-point with someone in another school.** Without knowing both ISRs the comparison is meaningless.",
      "**Expecting annual progression.** Leadership progression requires sustained high performance, not just a satisfactory year.",
      "**Forgetting the pension tier jump.** A promotion that crosses a tier boundary delivers less net gain than the gross figure suggests.",
      "**Giving up a large TLR for a low leadership point.** Run both packages through a calculator before accepting.",
      "**Not checking the ISR before applying.** A job advert quoting a wide range may only fund the bottom two points in practice.",
      "**Ignoring the overlap rule.** If a deputy post overlaps the head's ISR, ask why — it may signal an unusual structure.",
    ]},

    { kind: "h2", text: "Reviewing your own leadership pay" },
    { kind: "p", text: "Governing bodies must review leadership pay annually, normally by 31 December, and must have a published pay policy setting out how decisions are made. If you believe your ISR no longer reflects the job, the route is a formal pay review request rather than an informal conversation." },
    { kind: "p", text: "Grounds that carry weight include a significant and permanent change in the size or complexity of the school, a substantial expansion of your remit, taking on system leadership across a trust, or a demonstrable market recruitment problem. Practical steps are set out in the guide to [moving up the leadership pay scale](/how-to-move-up-leadership-pay-scale/)." },
  ],
  faq: [
    { question: "What is the leadership pay scale for 2026/27?", answer: "The leadership spine runs from £53,585 at L1 to £148,829 at L43 in the rest of England, following the 3.5% STPCD award from 1 September 2026. Inner London runs from £63,708 to £158,862, outer London from £57,837 to £153,041, and the London fringe from £55,060 to £150,301." },
    { question: "How much is L9 on the teacher leadership scale?", answer: "L9 is approximately £65,095 in the rest of England, £66,667 in the fringe, £69,615 in outer London and £75,819 in inner London for 2026/27. L9 is a typical point for an assistant head in a larger primary or a mid-scale secondary assistant head." },
    { question: "What is L12 on the leadership scale?", answer: "L12 is around £70,022 in the rest of England and £80,933 in inner London for 2026/27. It is a common point for deputy headteachers in secondary schools and experienced deputies in large primaries." },
    { question: "What is an individual school range?", answer: "An individual school range, or ISR, is the seven-point slice of the 43-point leadership spine that a governing body assigns to a specific leadership post. You are appointed somewhere within that range and progress through it as your performance is reviewed. Different schools set different ISRs for similar jobs." },
    { question: "Is leadership pay progression automatic?", answer: "No. Unlike the main pay range, where progression is normally annual subject to satisfactory performance, leadership progression requires sustained high performance against your objectives. Most schools expect two consecutive successful years before awarding a point, and you cannot progress beyond the top of your ISR." },
    { question: "Do assistant heads and deputies get paid on the same scale as headteachers?", answer: "They use the same 43-point leadership spine, but their individual school ranges should not normally overlap with the headteacher's range. In practice assistant heads sit lowest on the spine, deputies above them, and the headteacher above both." },
    { question: "Is it worth moving from UPS3 to leadership?", answer: "Financially, only if the ISR is high enough. U3 pays £52,835 and L1 pays £53,585 — a gross difference of £750, worth roughly £30 a month after deductions. A teacher on U3 with a TLR 1 can earn more than an assistant head on a low leadership point, so compare total packages rather than headline scale names." },
    { question: "Is there a different school leadership pay scale in Wales?", answer: "Welsh maintained-school leaders are paid on an IWPRB-negotiated scale rather than the STPCD. For 2026/27 it mirrors the English endpoints of £53,585 to £148,829, so the figures on this page apply, but future Welsh awards are set independently and can diverge from England." },
    { question: "Do academies have to use the leadership pay scale?", answer: "No. Academy trusts set their own pay policies and can create their own leadership bands, although most use the STPCD spine as a reference point. Check the trust's pay policy before comparing an academy leadership salary with a maintained-school ISR, because the same job title can sit outside the national framework entirely." },
    { question: "How does London weighting work on the leadership scale?", answer: "It is built into a higher spine rather than paid as a separate allowance. The inner London premium is roughly £10,000 to £11,000 in cash across the whole spine, which is nearly 19% at L1 but under 7% at L43." },
  ],
  sources: SOURCES,
  updated: UPDATED,
};

const headTeacherPage: PageContent = {
  slug: "head-teacher-salary",
  hub: "leadership",
  title: "Head Teacher Salary UK 2026/27",
  metaTitle: "Head Teacher Salary UK 2026/27 — Pay by School Group Size",
  metaDescription:
    "What headteachers earn in 2026/27. School group sizes 1 to 8 explained, indicative pay ranges for primary and secondary heads, and how governors set the range.",
  primaryKeyword: "head teacher salary uk",
  secondaryKeywords: [
    "headteacher salary", "average head teacher salary uk", "head teacher pay",
    "headteacher pay scale", "head teacher salary", "primary head teacher salary",
    "secondary head teacher salary", "executive headteacher salary",
    "primary school head teacher salary uk", "secondary school head teacher salary uk",
    "head of year teacher salary uk", "head of department teacher salary uk",
    "how much do headteachers earn",
  ],
  calculator: "pay-scale",
  calculatorPreset: { scale: "leadership" },
  intro:
    "Headteacher pay is anchored to school group size, which is worked out from pupil numbers weighted by key stage. This page explains how the group is calculated, what each group typically pays in 2026/27, and the discretion governors have to go above the range.",
  keyTakeaways: [
    "Headteacher pay sits on the 43-point leadership spine, from £53,585 to £148,829 in the rest of England.",
    "School group size — from Group 1 to Group 8 — is the starting point for setting a head's pay range.",
    "Group size is calculated from a total unit score: 7 units per pupil up to Year 6, 9 units for Years 7 to 11, and 13 units for Year 12 and above.",
    "A typical primary head sits somewhere between L6 and L22; a secondary head between L21 and L31.",
    "Governors can pay above the range in exceptional circumstances, but discretionary payments are capped at 25% above the ISR maximum without external advice.",
  ],
  blocks: [
    { kind: "h2", text: "How much do headteachers earn in 2026/27?" },
    { kind: "p", text: "There is no single headteacher salary. Pay depends almost entirely on the size and complexity of the school, and the spread is enormous — a head of a small rural primary and the head of a large London secondary are both on the leadership spine, but they can be more than £80,000 apart." },
    { kind: "p", text: "The statutory floor for any headteacher post is L1, £53,585 in the rest of England for 2026/27. The statutory ceiling is L43, £148,829. Between those two figures, the group size framework does most of the work." },
    { kind: "table", caption: "Headteacher pay boundaries 2026/27", head: ["Region", "Minimum (L1)", "Maximum (L43)"], rows: [
      ["Rest of England", "£53,585", "£148,829"],
      ["London Fringe", "£55,060", "£150,301"],
      ["Outer London", "£57,837", "£153,041"],
      ["Inner London", "£63,708", "£158,862"],
    ]},

    { kind: "h2", text: "School group size explained" },
    { kind: "p", text: "Every school is assigned to one of eight groups. The group is determined by a total unit score, which converts pupil numbers into a single figure that reflects the fact that older pupils are more expensive and more complex to educate." },
    { kind: "h3", text: "How the unit score is calculated" },
    { kind: "p", text: "Each pupil on roll contributes a number of units depending on their year group. You add up the units for the whole school to get the total unit score." },
    { kind: "table", caption: "Pupil unit weightings", head: ["Year group", "Units per pupil"], rows: [
      ["Nursery and Reception to Year 6", "7"],
      ["Year 7 to Year 11", "9"],
      ["Year 12 and above (sixth form)", "13"],
    ]},
    { kind: "p", text: "So a 420-pupil primary school scores 420 × 7 = 2,940 units. An 1,100-pupil 11–18 secondary with 200 sixth formers scores (900 × 9) + (200 × 13) = 10,700 units." },
    { kind: "h3", text: "Group boundaries" },
    { kind: "table", caption: "School group by total unit score", head: ["Group", "Total unit score", "Typical school"], rows: [
      ["Group 1", "Up to 1,000", "Very small primary (under 145 pupils)"],
      ["Group 2", "1,001 – 2,200", "Small to average primary"],
      ["Group 3", "2,201 – 3,500", "Average to large primary"],
      ["Group 4", "3,501 – 5,000", "Large primary or very small secondary"],
      ["Group 5", "5,001 – 8,000", "Small secondary"],
      ["Group 6", "8,001 – 11,000", "Average secondary"],
      ["Group 7", "11,001 – 17,000", "Large secondary with sixth form"],
      ["Group 8", "17,001 and over", "Very large secondary or all-through school"],
    ]},
    { kind: "callout", tone: "info", title: "Check the current STPCD for the statutory ranges", text: "The STPCD publishes a minimum and maximum spine point for each group. Those statutory boundaries are the definitive figures for setting an ISR — the indicative ranges below are observed sector patterns to help you benchmark, not a substitute for the document." },

    { kind: "h2", text: "Indicative headteacher pay by group size" },
    { kind: "p", text: "These are typical individual school ranges observed across the sector for 2026/27, using rest of England figures. Your governing body sets the actual range within the statutory boundaries for your group." },
    { kind: "table", caption: "Typical headteacher ISR by group (rest of England, indicative)", head: ["Group", "Typical ISR", "Salary range"], rows: [
      ["Group 1", "L6 – L12", "£60,514 – £70,022"],
      ["Group 2", "L8 – L14", "£63,531 – £73,513"],
      ["Group 3", "L11 – L17", "£68,340 – £79,077"],
      ["Group 4", "L14 – L20", "£73,513 – £85,063"],
      ["Group 5", "L18 – L24", "£81,024 – £93,754"],
      ["Group 6", "L21 – L27", "£87,157 – £100,851"],
      ["Group 7", "L24 – L30", "£93,754 – £108,485"],
      ["Group 8", "L28 – L34", "£103,334 – £119,570"],
    ]},
    { kind: "p", text: "Add roughly £10,000 to £11,000 for inner London, £4,000 to £5,000 for outer London, and £1,500 for the fringe. The full regional figures for every spine point are on the [leadership pay scale page](/leadership-pay-scale/)." },

    { kind: "h2", text: "Primary versus secondary headteacher pay" },
    { kind: "p", text: "The group size system means the primary/secondary gap is really a size gap. A large all-through primary can out-score a small secondary and pay its head more." },
    { kind: "table", caption: "Worked comparison of two schools", head: ["School", "Pupils", "Unit score", "Group", "Typical head salary"], rows: [
      ["Village primary", "140 (all primary)", "980", "Group 1", "£60,514 – £70,022"],
      ["Two-form primary", "420 (all primary)", "2,940", "Group 3", "£68,340 – £79,077"],
      ["Small 11–16 secondary", "600 (all KS3/4)", "5,400", "Group 5", "£81,024 – £93,754"],
      ["11–18 secondary", "1,100 inc. 200 sixth form", "10,700", "Group 6", "£87,157 – £100,851"],
    ]},
    { kind: "p", text: "This is why headship of a large primary can pay more than a deputy headship in a secondary, and why moving from a Group 3 to a Group 6 headship is one of the biggest single pay jumps available in teaching." },

    { kind: "h2", text: "Going above the range" },
    { kind: "p", text: "Governing bodies have discretion to pay a headteacher above the maximum of the ISR, but the STPCD constrains it. Discretionary payments — for example for taking on an additional school, leading a federation, or genuinely exceptional recruitment difficulty — should not normally take total salary more than 25% above the ISR maximum." },
    { kind: "p", text: "Going beyond that 25% ceiling requires the governing body to seek external independent advice and to document a clear rationale. In academies and multi-academy trusts the STPCD does not bind pay decisions in the same way, but trusts are subject to scrutiny from the ESFA and their own funding agreements on executive pay." },
    { kind: "callout", tone: "warn", title: "Executive pay is under close scrutiny", text: "Trusts paying senior leaders above £100,000 are routinely challenged to justify it in their annual accounts. Very high MAT executive salaries attract regulatory attention, so a large advertised package usually comes with a correspondingly large remit." },

    { kind: "h2", text: "What headteacher pay is worth after deductions" },
    { kind: "p", text: "Headship salaries sit in the higher tax bands and the top pension tiers, so the net figure is a long way below the headline." },
    { kind: "table", caption: "Indicative take-home for headteacher salaries, rest of England 2026/27", head: ["Salary", "Pension tier", "Approx. monthly take-home"], rows: [
      ["£70,022 (L12)", "10.2%", "£3,907"],
      ["£87,157 (L21)", "11.7%", "£4,583"],
      ["£103,334 (L28)", "12.7%", "£5,163"],
      ["£119,570 (L34)", "12.7%", "£5,574"],
    ]},
    { kind: "p", text: "Above £100,000 the personal allowance tapers away at £1 for every £2 earned, creating an effective 60% marginal rate between £100,000 and £125,140. A head moving from L26 to L28 crosses straight into that band. Run your own figures through the [teacher pay calculator](/teacher-pay-calculator/) to see the real net effect." },

    { kind: "h2", text: "Middle leaders versus the leadership group" },
    { kind: "p", text: "Head of year and head of department salaries are a frequent source of confusion. Neither role is part of the leadership group. A head of year or head of department in England is normally a classroom teacher on the main or upper pay range who receives a teaching and learning responsibility payment on top — typically £3,650 to £8,912 for TLR 2 or £10,530 to £17,819 for TLR 1 in 2026/27." },
    { kind: "p", text: "So a U3 teacher with a TLR 1 earns up to £63,365 — more than some assistant heads. The distinction matters when comparing vacancies: a post advertised with an L-point range is a leadership group post on the [leadership pay scale](/leadership-pay-scale/), while a post advertised as salary plus TLR is a middle-leadership role. Both are legitimate career routes, but they are paid from entirely different frameworks." },

    { kind: "h2", text: "Common questions about the route to headship" },
    { kind: "p", text: "Most heads arrive via deputy headship, and the pay step is usually significant — often six to ten spine points. See [deputy headteacher pay](/deputy-head-teacher-salary/) for the level below, and [how to move up the leadership pay scale](/how-to-move-up-leadership-pay-scale/) for progression mechanics once you are in post." },
    { kind: "p", text: "For a broader picture of where headship sits against classroom and middle leadership pay across the profession, see the [UK teacher salary overview](/teacher-salary-uk/)." },
  ],
  faq: [
    { question: "What is the average head teacher salary in the UK?", answer: "There is no single average because pay follows school size. A small primary headteacher typically earns £60,000 to £70,000, an average primary head £68,000 to £79,000, and a secondary head £87,000 to £109,000 in the rest of England for 2026/27. Inner London adds roughly £10,000 to £11,000." },
    { question: "How is headteacher pay decided?", answer: "The governing body sets a seven-point individual school range on the leadership spine. The starting point is the school group, calculated from a total unit score based on pupil numbers weighted by key stage. Governors then adjust for the specific demands of the role within the statutory boundaries for that group." },
    { question: "What is school group size?", answer: "It is a classification from Group 1 to Group 8 based on a total unit score. Each pupil up to Year 6 counts 7 units, Years 7 to 11 count 9 units, and Year 12 and above count 13 units. A 420-pupil primary scores 2,940 units, placing it in Group 3." },
    { question: "How much does a primary school head teacher earn?", answer: "Most primary headteachers fall in Groups 1 to 4, giving typical ranges from about £60,514 at the bottom of a small school range to £85,063 at the top of a large primary range in the rest of England for 2026/27." },
    { question: "How much does a secondary head teacher earn?", answer: "Secondary schools usually fall in Groups 5 to 8. Typical ranges run from around £81,024 for a small secondary to £119,570 at the top of a very large school range in the rest of England, with inner London schools paying roughly £11,000 more." },
    { question: "Can a headteacher be paid more than the top of their range?", answer: "Yes, but with limits. Governors can make discretionary payments for additional responsibilities such as leading a federation, though total salary should not normally exceed 25% above the ISR maximum. Going beyond that requires external independent advice and a documented rationale." },
    { question: "Do academy headteachers get paid on the same scale?", answer: "Academies and free schools are not bound by the STPCD and can set their own pay. In practice most benchmark against the leadership spine, but multi-academy trust executive salaries can be considerably higher and are subject to scrutiny from the ESFA and in published accounts." },
    { question: "What does a head of year or head of department earn compared with a headteacher?", answer: "Heads of year and departments are not on the leadership spine. They are classroom teachers paid on the main or upper pay range plus a TLR of £3,650 to £17,819 depending on level, so a typical total is £40,000 to £65,000. That is well below primary headteacher pay but can exceed an assistant head on a low ISR." },
    { question: "What is the highest a headteacher can be paid?", answer: "The statutory maximum on the leadership spine is L43, which is £148,829 in the rest of England and £158,862 in inner London for 2026/27. Executive heads and MAT chief executives can be paid more, particularly outside the STPCD framework, though such packages attract regulatory scrutiny." },
  ],
  sources: SOURCES,
  updated: UPDATED,
};

const deputyHeadPage: PageContent = {
  slug: "deputy-head-teacher-salary",
  hub: "leadership",
  title: "Deputy Head Teacher Salary UK 2026/27",
  metaTitle: "Deputy Head Teacher Salary 2026/27 — Primary & Secondary",
  metaDescription:
    "Deputy headteacher pay for 2026/27. Typical leadership spine points for primary and secondary deputies, regional figures, and how the range relates to the head's.",
  primaryKeyword: "deputy head teacher salary",
  secondaryKeywords: [
    "deputy head teacher salary uk", "deputy head teacher salary primary uk",
    "deputy headteacher salary", "deputy head salary", "deputy head teacher pay",
    "deputy headteacher pay scale", "deputy head teacher salary secondary",
    "deputy head teacher salary scotland", "deputy head teacher salary wales",
    "average deputy head teacher salary uk",
    "deputy head teacher salary secondary school uk",
    "primary school deputy head teacher salary", "deputy head teacher salary london",
  ],
  calculator: "pay-scale",
  calculatorPreset: { scale: "leadership" },
  intro:
    "Deputy headteachers sit in the middle of the leadership spine, typically between L8 and L20 depending on phase and school size. This page sets out the realistic ranges for 2026/27, how the deputy range is anchored to the headteacher's, and what the step up actually pays.",
  keyTakeaways: [
    "Primary deputies typically sit between L8 and L16, roughly £63,531 to £77,177 in the rest of England.",
    "Secondary deputies typically sit between L12 and L20, roughly £70,022 to £85,063.",
    "The deputy range should not normally overlap with the headteacher's individual school range.",
    "Inner London deputies earn approximately £10,700 to £11,200 more than the same post outside London.",
    "The step from assistant head to deputy is usually four to six spine points, worth around £6,000 to £10,000 gross.",
  ],
  blocks: [
    { kind: "h2", text: "How much does a deputy headteacher earn?" },
    { kind: "p", text: "Deputy headteacher pay is set on the same 43-point leadership spine as every other leadership post, but deputies occupy a fairly predictable band in the middle of it. The two factors that move the number are phase — primary or secondary — and the size of the school." },
    { kind: "table", caption: "Typical deputy headteacher pay 2026/27, rest of England", head: ["Setting", "Typical ISR", "Salary range"], rows: [
      ["Small primary (Group 1–2)", "L6 – L12", "£60,514 – £70,022"],
      ["Average primary (Group 3)", "L8 – L14", "£63,531 – £73,513"],
      ["Large primary (Group 4)", "L10 – L16", "£66,698 – £77,177"],
      ["Small secondary (Group 5)", "L11 – L17", "£68,340 – £79,077"],
      ["Average secondary (Group 6)", "L13 – L19", "£71,746 – £83,019"],
      ["Large secondary (Group 7–8)", "L16 – L22", "£77,177 – £89,303"],
    ]},
    { kind: "p", text: "These are observed sector patterns rather than statutory values. The definitive figure for any post is the individual school range published in the job advert and set out in the school's pay policy." },

    { kind: "h2", text: "Deputy head pay by region" },
    { kind: "p", text: "London weighting applies to the whole leadership spine, so a deputy in inner London on the same spine point earns substantially more than a counterpart elsewhere." },
    { kind: "table", caption: "Selected deputy-range spine points across regions, 2026/27", head: ["Point", "Rest of England", "Fringe", "Outer London", "Inner London"], rows: [
      ["L8", "£63,531", "£65,091", "£68,020", "£74,188"],
      ["L10", "£66,698", "£68,280", "£71,246", "£77,487"],
      ["L12", "£70,022", "£71,624", "£74,625", "£80,933"],
      ["L14", "£73,513", "£75,132", "£78,165", "£84,532"],
      ["L16", "£77,177", "£78,813", "£81,872", "£88,291"],
      ["L18", "£81,024", "£82,673", "£85,755", "£92,218"],
      ["L20", "£85,063", "£86,722", "£89,822", "£96,319"],
    ]},

    { kind: "h2", text: "How the deputy range relates to the headteacher's" },
    { kind: "p", text: "The STPCD expects that pay ranges for deputy and assistant headteachers should not normally overlap with the headteacher's individual school range. That single rule shapes deputy pay more than anything else." },
    { kind: "p", text: "In a Group 3 primary where the head is on an ISR of L11 to L17, the deputy range will normally top out at or below L11 — so something like L5 to L11. In a Group 6 secondary where the head sits on L21 to L27, a deputy range of L15 to L21 is typical." },
    { kind: "callout", tone: "info", title: "Why some deputy jobs pay unusually well", text: "Where a school has two deputies, or where the deputy carries a substantial system-leadership or trust-wide brief, governors can justify a higher range. Federated schools and schools in challenging circumstances also tend to pay deputies towards the top of the normal band." },
    { kind: "p", text: "For the level above, see the [headteacher salary guide](/head-teacher-salary/) and its explanation of the group size framework." },

    { kind: "h2", text: "Deputy head versus assistant head" },
    { kind: "p", text: "The step from assistant to deputy headteacher is usually four to six spine points. In cash terms that is meaningful, but the pension tier can eat into it." },
    { kind: "table", caption: "Typical assistant-to-deputy step, average secondary, rest of England", head: ["Role", "Typical point", "Salary", "Pension tier", "Approx. monthly take-home"], rows: [
      ["Assistant head", "L9", "£65,095", "10.2%", "£3,694"],
      ["Deputy head", "L15", "£75,322", "11.7%", "£4,080"],
      ["Difference", "+6 points", "+£10,227", "+1.5pp", "+£386"],
    ]},
    { kind: "p", text: "A £10,227 gross increase delivers roughly £386 a month extra. The gap between gross and net is wider than many people expect because the move crosses the £72,534 pension tier boundary as well as taking more income into the 40% band. Model your own figures with the [teacher pay calculator](/teacher-pay-calculator/). Full detail on the level below is in the [assistant headteacher salary guide](/assistant-head-teacher-salary/)." },

    { kind: "h2", text: "What deputy heads actually do for the money" },
    { kind: "p", text: "Pay ranges reflect accountability, and deputy headship is where accountability changes character. Typical elements of the role include deputising fully for the head, holding a whole-school portfolio such as curriculum, behaviour or safeguarding, line-managing other leaders, and carrying statutory responsibilities as designated safeguarding lead in many schools." },
    { kind: "p", text: "Most deputies also retain a teaching commitment. Unlike classroom teachers, leadership group members are not entitled to guaranteed PPA time in the same way, and they have no limit on directed time — the STPCD directed time provisions do not apply to the leadership group." },
    { kind: "callout", tone: "warn", title: "Directed time protections do not apply to leadership", text: "The 1,265-hour directed time limit and guaranteed PPA entitlement apply to classroom teachers, not to the leadership group. This is a genuine and often underestimated part of the trade-off when moving from a TLR post into leadership." },

    { kind: "h2", text: "Pension impact of deputy headship" },
    { kind: "p", text: "Because the [Teachers' Pension Scheme](/teacher-pension/) is career average rather than final salary, years spent as a deputy build pension at the higher salary permanently. Each year you accrue 1/57th of your pensionable pay, revalued annually." },
    { kind: "p", text: "A deputy on £75,322 builds around £1,321 of annual pension for that single year, compared with roughly £927 for a teacher on U3. Over a ten-year deputy headship, that difference compounds into a materially larger retirement income." },

    { kind: "h2", text: "Deputy head pay in Scotland, Wales and London" },
    { kind: "p", text: "The figures above are England and Wales. Deputy head teacher salaries in Scotland are set by the Scottish Negotiating Committee for Teachers on a separate depute head scale, and the numbers are not interchangeable with the English leadership spine — a Scottish depute head is paid from a different framework with different progression rules. Northern Ireland similarly runs its own leadership arrangements." },
    { kind: "p", text: "In Wales, deputies in maintained schools are paid on the IWPRB-negotiated version of the leadership spine, which currently matches the English endpoints. A deputy head teacher salary in inner London works exactly as the regional table shows: the same spine points simply carry higher values, so an L12 deputy earns £80,933 in inner London against £70,022 in the rest of England — a premium of nearly £10,900 for the identical point." },

    { kind: "h2", text: "Common mistakes when taking a deputy post" },
    { kind: "ul", items: [
      "**Not asking where in the ISR you would start.** An advert quoting L12 to L18 may only offer L12 to an internal candidate.",
      "**Assuming the range is negotiable after appointment.** Starting point is much easier to negotiate before you accept.",
      "**Giving up a TLR 1 without checking the maths.** A U3 teacher with a £15,000 TLR 1 earns £67,835, more than many primary deputies.",
      "**Overlooking the loss of directed time protections.** Leadership hours are not capped.",
      "**Ignoring the pension tier boundary at £72,534.** Crossing it costs 1.5 percentage points on your entire salary.",
      "**Not checking whether the post is one of two deputies.** A sole deputy in a large school carries far more than the pay difference suggests.",
    ]},
  ],
  faq: [
    { question: "How much does a deputy head teacher earn in the UK?", answer: "Most deputy headteachers earn between £63,531 and £89,303 in the rest of England for 2026/27, depending on phase and school size. Primary deputies typically sit between L8 and L16 and secondary deputies between L12 and L20 on the leadership spine." },
    { question: "How much does a primary deputy head teacher earn?", answer: "A primary deputy typically earns between £60,514 and £77,177 in the rest of England for 2026/27, depending on school group size. In a small Group 1 or 2 primary the range is usually L6 to L12; in a large Group 4 primary it is more likely L10 to L16." },
    { question: "Can a deputy head be paid more than the headteacher?", answer: "It should not normally happen. The STPCD expects deputy and assistant head ranges not to overlap with the headteacher's individual school range. In rare cases an experienced deputy at the top of their range in a large school might out-earn a new head of a very small school, but not within the same school." },
    { question: "How much more do deputy heads earn than assistant heads?", answer: "Typically four to six spine points, which is around £6,000 to £10,000 gross. Moving from L9 to L15 in the rest of England is an increase of £10,227 gross, worth roughly £386 a month after tax, National Insurance and the higher pension tier." },
    { question: "Do deputy heads get PPA time?", answer: "Not as a statutory entitlement. Guaranteed PPA time and the 1,265-hour directed time limit apply to classroom teachers, not to the leadership group. Most deputies negotiate a reduced teaching commitment, but there is no statutory protection on leadership hours." },
    { question: "What is L12 for a deputy head?", answer: "L12 is approximately £70,022 in the rest of England, £71,624 in the fringe, £74,625 in outer London and £80,933 in inner London for 2026/27. It is a very common point for secondary deputy headteachers and experienced primary deputies." },
    { question: "What is the average deputy head teacher salary in the UK?", answer: "Across primary and secondary settings, most UK deputy heads earn between roughly £63,500 and £89,300 in the rest of England for 2026/27, with inner London adding around £10,700 to £11,200. Scotland and Northern Ireland use separate negotiating frameworks with their own depute head scales." },
    { question: "Is deputy headship worth it financially?", answer: "It depends what you are giving up. If you currently hold a large TLR 1 on U3 you may be earning £63,000 to £68,000 already, which overlaps the bottom of many deputy ranges. Compare the total package including allowances, and factor in the loss of directed time protections." },
  ],
  sources: SOURCES,
  updated: UPDATED,
};

const assistantHeadPage: PageContent = {
  slug: "assistant-head-teacher-salary",
  hub: "leadership",
  title: "Assistant Head Teacher Salary UK 2026/27",
  metaTitle: "Assistant Head Teacher Salary 2026/27 — Leadership Pay",
  metaDescription:
    "Assistant headteacher pay for 2026/27. Typical L-points for primary and secondary AHTs, how the range is set, and whether the step up from a TLR is worth it.",
  primaryKeyword: "assistant head teacher salary",
  secondaryKeywords: [
    "assistant head teacher salary uk", "assistant headteacher salary",
    "average assistant head teacher salary uk",
    "assistant head teacher salary primary uk",
    "assistant head pay scale", "assistant headteacher pay",
    "what does an assistant head teacher earn",
    "assistant head vs deputy head salary",
    "assistant head salary uk", "assistant head teacher pay",
  ],
  calculator: "pay-scale",
  calculatorPreset: { scale: "leadership" },
  intro:
    "Assistant headteacher is the entry point to the leadership group for most teachers. Ranges typically start around L4 and rarely exceed L14. This page sets out the realistic figures for 2026/27 and compares the move against staying on a TLR.",
  keyTakeaways: [
    "Primary assistant heads typically sit between L4 and L10, roughly £57,641 to £66,698 in the rest of England.",
    "Secondary assistant heads typically sit between L6 and L14, roughly £60,514 to £73,513.",
    "The first leadership point, L1 at £53,585, is only £750 above the top of the upper pay range.",
    "A teacher on U3 with a TLR 1 can earn more than an assistant head on a low leadership point.",
    "Assistant headship is the point at which directed time protections and guaranteed PPA stop applying.",
  ],
  blocks: [
    { kind: "h2", text: "How much does an assistant headteacher earn?" },
    { kind: "p", text: "Assistant headteacher is the first rung of the leadership group, and the pay reflects that. Most AHT posts are advertised somewhere between L4 and L14 on the leadership spine, with the exact range depending on phase, school size and the scope of the portfolio." },
    { kind: "table", caption: "Typical assistant headteacher pay 2026/27, rest of England", head: ["Setting", "Typical ISR", "Salary range"], rows: [
      ["Small primary (Group 1–2)", "L3 – L9", "£56,256 – £65,095"],
      ["Average primary (Group 3)", "L4 – L10", "£57,641 – £66,698"],
      ["Large primary (Group 4)", "L6 – L12", "£60,514 – £70,022"],
      ["Small secondary (Group 5)", "L6 – L12", "£60,514 – £70,022"],
      ["Average secondary (Group 6)", "L8 – L14", "£63,531 – £73,513"],
      ["Large secondary (Group 7–8)", "L10 – L16", "£66,698 – £77,177"],
    ]},
    { kind: "p", text: "These are observed patterns across the sector, not statutory figures. The definitive range for any post is published in the advert and in the school's pay policy. Full spine values for all four England regions are on the [leadership pay scale page](/leadership-pay-scale/)." },

    { kind: "h2", text: "Assistant head pay across the regions" },
    { kind: "table", caption: "Common assistant-head spine points by region, 2026/27", head: ["Point", "Rest of England", "Fringe", "Outer London", "Inner London"], rows: [
      ["L4", "£57,641", "£59,155", "£62,000", "£68,005"],
      ["L6", "£60,514", "£62,052", "£64,940", "£71,029"],
      ["L8", "£63,531", "£65,091", "£68,020", "£74,188"],
      ["L10", "£66,698", "£68,280", "£71,246", "£77,487"],
      ["L12", "£70,022", "£71,624", "£74,625", "£80,933"],
      ["L14", "£73,513", "£75,132", "£78,165", "£84,532"],
    ]},

    { kind: "h2", text: "Is the step into leadership worth it?" },
    { kind: "p", text: "This is the single most important financial question for anyone considering an assistant headship, and the answer is genuinely not always yes." },
    { kind: "p", text: "The top of the [upper pay range](/upper-pay-range/) is £52,835. A TLR 2 adds between £3,650 and £8,912; a TLR 1 adds between £10,530 and £17,819. A head of department on U3 with a mid-range TLR 1 is therefore earning around £66,000 — comfortably more than an assistant head on L8." },
    { kind: "table", caption: "Comparing a middle leader with an assistant head, rest of England 2026/27", head: ["Position", "Base", "Allowance", "Total gross"], rows: [
      ["U3 + TLR 2 (mid)", "£52,835", "£6,281", "£59,116"],
      ["U3 + TLR 1 (min)", "£52,835", "£10,530", "£63,365"],
      ["U3 + TLR 1 (mid)", "£52,835", "£14,175", "£67,010"],
      ["Assistant head L6", "£60,514", "—", "£60,514"],
      ["Assistant head L10", "£66,698", "—", "£66,698"],
      ["Assistant head L14", "£73,513", "—", "£73,513"],
    ]},
    { kind: "callout", tone: "tip", title: "Do the comparison before you apply", text: "If you hold a TLR 1, an assistant headship below about L10 may be a pay cut in real terms once you account for the loss of directed time limits. Put both packages through the [teacher pay calculator](/teacher-pay-calculator/) — remember TLRs are entered as annual pound amounts." },

    { kind: "h2", text: "What changes when you join the leadership group" },
    { kind: "p", text: "The pay change is only part of the picture. Joining the leadership group changes your conditions of service in ways that are easy to overlook." },
    { kind: "ul", items: [
      "**Directed time no longer applies.** The 1,265-hour annual limit covers classroom teachers only.",
      "**Guaranteed PPA time stops being an entitlement.** Most AHTs still get non-contact time, but it is negotiated rather than protected.",
      "**Progression becomes discretionary.** You move up your ISR on sustained high performance, not annually.",
      "**Your range is capped.** Once you reach the top of a seven-point ISR the only route up is a wider range or a new post.",
      "**Accountability broadens.** You are judged on whole-school outcomes, not just your subject or phase.",
    ]},

    { kind: "h2", text: "Typical assistant head portfolios" },
    { kind: "p", text: "The scope of the portfolio is the main justification governors use when setting the range at the higher end. Common briefs include teaching and learning, behaviour and attitudes, safeguarding and designated safeguarding lead duties, curriculum and assessment, inclusion and SEND, sixth form or key stage leadership, and staff development and ECT induction." },
    { kind: "p", text: "A portfolio carrying statutory responsibility — designated safeguarding lead in particular — generally supports a higher range than a purely developmental brief." },

    { kind: "h2", text: "What assistant head pay is worth after deductions" },
    { kind: "p", text: "Leadership salaries sit in the 10.2% and 11.7% pension tiers and take a large slice of income into the 40% tax band, so the net figure moves much more slowly than the gross." },
    { kind: "table", caption: "Indicative monthly take-home, assistant head points, rest of England 2026/27", head: ["Point", "Salary", "Pension tier", "Approx. monthly take-home"], rows: [
      ["L4", "£57,641", "10.2%", "£3,372"],
      ["L6", "£60,514", "10.2%", "£3,496"],
      ["L8", "£63,531", "10.2%", "£3,626"],
      ["L10", "£66,698", "10.2%", "£3,763"],
      ["L12", "£70,022", "10.2%", "£3,907"],
      ["L14", "£73,513", "11.7%", "£4,003"],
    ]},
    { kind: "p", text: "Look closely at the last row. Moving from L12 to L14 is a gross rise of £3,491, but the net gain is only £96 a month. Crossing £72,534 shifts you from the 10.2% pension tier to 11.7%, and that 1.5 percentage point increase applies to your entire salary, not just the part above the threshold." },
    { kind: "callout", tone: "warn", title: "The tier boundary at £72,534 is the sharpest step on the spine", text: "A promotion that lands just above this figure delivers noticeably less than the gross increase suggests. If you are negotiating a starting point near the boundary, one extra point below it can be worth more per pound than one point above it." },
    { kind: "p", text: "It is worth putting the comparison the other way round too. A head of department on U3 with a mid-range TLR 1 takes home about £3,777 a month — more than an assistant head at L10 on £3,763, despite the leadership title." },

    { kind: "h2", text: "How to get an assistant headship" },
    { kind: "p", text: "Assistant headships attract strong fields, and the selection process looks for evidence of impact beyond your own classroom or department. Most successful candidates arrive from a substantial TLR post." },
    { kind: "h3", text: "What appointment panels look for" },
    { kind: "ul", items: [
      "**Impact beyond your own team.** Whole-school work, cross-phase projects, or leading an initiative outside your subject.",
      "**Data literacy.** Being able to interrogate school performance data and explain what you would do about it.",
      "**Developing other adults.** Coaching, mentoring ECTs, running CPD that changed practice.",
      "**Strategic thinking.** Evidence you can plan over three years, not just one term.",
      "**Safeguarding credibility.** Many AHT posts carry deputy DSL duties, so relevant training matters.",
    ]},
    { kind: "h3", text: "Qualifications and preparation" },
    { kind: "p", text: "There is no mandatory qualification for assistant headship. The NPQ for Senior Leadership (NPQSL) is the most commonly held and is well regarded, but it is not a requirement and panels weigh demonstrated impact more heavily than certificates. Acting-up opportunities, secondments and trust-wide projects are often more persuasive than a course." },
    { kind: "h3", text: "Negotiating your starting point" },
    { kind: "p", text: "The single most valuable thing you can do is ask, before accepting, where in the range you would start and what the criteria for progression are. Schools frequently appoint at the bottom of the ISR by default, but a strong internal or experienced candidate can often start a point or two higher. Once you have signed, the only route up is the annual review cycle." },
    { kind: "callout", tone: "tip", title: "Ask three questions before accepting", text: "Where in the range would I start? What has to be true for me to move a point? Is this range under review in the next two years? The answers tell you far more about the real value of the post than the advertised range does." },

    { kind: "h2", text: "Progressing beyond assistant headship" },
    { kind: "p", text: "Most assistant heads either progress within their ISR, move to a larger school for a wider range, or step up to deputy headship. The step to deputy is typically four to six spine points — see [deputy headteacher pay](/deputy-head-teacher-salary/) for the detail." },
    { kind: "p", text: "Because the [Teachers' Pension Scheme](/teacher-pension/) is career average, every year at a higher salary permanently increases your retirement income, so the timing of the step up matters more than it would under a final-salary scheme. Guidance on securing progression is in the guide to [moving up the leadership pay scale](/how-to-move-up-leadership-pay-scale/)." },
  ],
  faq: [
    { question: "How much does an assistant head teacher earn?", answer: "Most assistant headteachers earn between £57,641 and £73,513 in the rest of England for 2026/27. Primary AHTs typically sit between L4 and L10, and secondary AHTs between L6 and L14 on the leadership spine. Inner London adds roughly £10,000 to £11,000." },
    { question: "What L point is an assistant head teacher?", answer: "There is no fixed point. Typical individual school ranges start around L3 to L6 and top out between L10 and L16, depending on school size and the scope of the portfolio. Larger secondary schools tend to set higher ranges than small primaries." },
    { question: "Is assistant head better paid than a head of department?", answer: "Not always. A head of department on U3 with a mid-range TLR 1 earns around £67,010, which is more than an assistant head on L10 (£66,698). Compare the total package including allowances before assuming leadership pays more." },
    { question: "Do assistant heads still teach?", answer: "Almost always, yes. Most assistant headteachers retain a substantial teaching timetable, particularly in primary schools where an AHT may still be a full-time class teacher with a leadership allowance built into their range." },
    { question: "Do assistant heads get PPA time?", answer: "Not as a statutory entitlement. Guaranteed PPA and the 1,265-hour directed time limit apply to classroom teachers only. Leadership group members negotiate non-contact time with their headteacher, but it is not legally protected." },
    { question: "What is the average assistant head teacher salary in the UK?", answer: "Most UK assistant heads earn between £57,641 and £73,513 in the rest of England for 2026/27, with typical primary AHTs on L4 to L10 and secondary AHTs on L6 to L14. Inner London ranges add roughly £10,000 to £11,200 at the same spine points." },
    { question: "Is an assistant head higher than a head of year?", answer: "In pay terms not necessarily. A head of year is a middle leader paid on the main or upper range plus a TLR, while an assistant head is on the leadership spine. A U3 head of year with a large TLR 1 can out-earn an assistant head on a low point, but the assistant head role carries whole-school accountability and leadership group conditions." },
    { question: "How do you get promoted from assistant to deputy head?", answer: "Usually by applying for a deputy post, often at a different school. Internal promotion happens but is less common because it requires a vacancy. The step is typically four to six spine points, worth around £6,000 to £10,000 gross." },
  ],
  sources: SOURCES,
  updated: UPDATED,
};

const leadPractitionerPage: PageContent = {
  slug: "lead-practitioner-pay-scale",
  hub: "leadership",
  title: "Lead Practitioner Pay Scale 2026/27",
  metaTitle: "Lead Practitioner Pay Scale 2026/27 — LP Range & Salary",
  metaDescription:
    "The lead practitioner pay range for 2026/27: £53,847 to £81,860 outside London. What the role is, how the range is set, and how it compares with leadership pay.",
  primaryKeyword: "lead practitioner pay scale",
  secondaryKeywords: [
    "lead practitioner scale", "what is a lead practitioner",
    "lead practitioner teacher salary", "lead practitioner salary",
    "lead practitioner pay", "advanced skills teacher pay",
    "lead practitioner pay range", "excellent teacher scheme",
    "lead practitioner jobs salary", "how much do lead practitioners earn",
  ],
  calculator: "pay-scale",
  calculatorPreset: { scale: "lead-practitioner" },
  intro:
    "Lead practitioner is the pay route for outstanding classroom teachers who want to stay in the classroom rather than move into management. The range runs from £53,847 to £81,860 in the rest of England for 2026/27 — higher than the upper pay range and overlapping the leadership spine.",
  keyTakeaways: [
    "The lead practitioner range is £53,847 to £81,860 in the rest of England, and £64,023 to £92,043 in inner London.",
    "It is a separate range from both the upper pay range and the leadership spine, though it overlaps the bottom of leadership.",
    "The role exists to reward excellent teaching and modelling of practice, not line management.",
    "Schools set an individual range within the national minimum and maximum, as they do for leadership posts.",
    "It replaced the old Advanced Skills Teacher and Excellent Teacher schemes.",
  ],
  blocks: [
    { kind: "h2", text: "What is a lead practitioner?" },
    { kind: "p", text: "A lead practitioner is a teacher whose primary purpose is modelling and leading the improvement of teaching skills across a school or group of schools. The STPCD created the role to give exceptional classroom teachers a well-paid career route that does not require moving into senior management." },
    { kind: "p", text: "The distinction matters. A deputy head is paid for accountability and whole-school management. A lead practitioner is paid for excellence in teaching and for developing that excellence in others. In practice the role usually involves a substantial teaching commitment, coaching and mentoring colleagues, leading CPD, developing curriculum and assessment practice, and often working across a trust or local partnership." },
    { kind: "p", text: "The role replaced two earlier schemes: Advanced Skills Teacher (AST) and Excellent Teacher. Both were abolished in 2013 and folded into the single lead practitioner range." },

    { kind: "h2", text: "Lead practitioner pay scale 2026/27" },
    { kind: "p", text: "The STPCD sets a national minimum and maximum for the lead practitioner range. Individual schools then set a range within those boundaries for each post." },
    { kind: "table", caption: "Lead practitioner national range 2026/27", head: ["Region", "Minimum", "Maximum"], rows: [
      ["Rest of England", "£53,847", "£81,860"],
      ["London Fringe", "£55,331", "£83,346"],
      ["Outer London", "£58,119", "£86,136"],
      ["Inner London", "£64,023", "£92,043"],
      ["Wales", "£53,847", "£81,860"],
    ]},
    { kind: "p", text: "Unlike the leadership group, the lead practitioner range is not divided into nationally numbered points. Schools commonly create their own scale of points within the range. The table below shows an even progression across the range for benchmarking purposes." },
    { kind: "table", caption: "Indicative lead practitioner progression, 2026/27", head: ["Point", "Rest of England", "Fringe", "Outer London", "Inner London"], rows: [
      ["LP1", "£53,847", "£55,331", "£58,119", "£64,023"],
      ["LP3", "£56,741", "£58,238", "£61,049", "£66,995"],
      ["LP5", "£59,791", "£61,298", "£64,126", "£70,105"],
      ["LP7", "£63,005", "£64,519", "£67,359", "£73,360"],
      ["LP9", "£66,392", "£67,909", "£70,754", "£76,765"],
      ["LP11", "£69,961", "£71,477", "£74,321", "£80,329"],
      ["LP13", "£73,722", "£75,233", "£78,067", "£84,058"],
      ["LP15", "£77,684", "£79,185", "£82,002", "£87,960"],
      ["LP17", "£81,860", "£83,346", "£86,136", "£92,043"],
    ]},
    { kind: "callout", tone: "warn", title: "These intermediate points are indicative", text: "The STPCD publishes only the minimum and maximum of the lead practitioner range. The points shown here are an even progression between those figures for comparison. Your school defines its own points within the range." },

    { kind: "h2", text: "Lead practitioner versus the upper pay range" },
    { kind: "p", text: "The lead practitioner range starts just above the top of the upper pay range and extends far beyond it. For an outstanding classroom teacher, it is by some distance the highest-paying route that keeps you teaching." },
    { kind: "table", caption: "Classroom teacher routes compared, rest of England 2026/27", head: ["Route", "Range", "Ceiling"], rows: [
      ["Main pay range", "£34,068 – £46,939", "£46,939"],
      ["Upper pay range", "£49,134 – £52,835", "£52,835"],
      ["U3 plus TLR 1", "£63,365 – £70,654", "£70,654"],
      ["Lead practitioner", "£53,847 – £81,860", "£81,860"],
      ["Leadership spine", "£53,585 – £148,829", "£148,829"],
    ]},
    { kind: "p", text: "A lead practitioner at the top of the range earns £81,860 — more than most primary headteachers and comparable with a deputy head in a large secondary. Details of the classroom route below it are on the [upper pay range page](/upper-pay-range/)." },

    { kind: "h2", text: "Lead practitioner versus leadership" },
    { kind: "p", text: "The two ranges overlap substantially. A lead practitioner at LP9 (£66,392) earns roughly the same as an assistant head at L10 (£66,698). The difference is in the nature of the job rather than the money." },
    { kind: "table", caption: "Comparing the two routes", head: ["Factor", "Lead practitioner", "Leadership group"], rows: [
      ["Primary purpose", "Modelling excellent teaching", "Whole-school accountability"],
      ["Teaching commitment", "Substantial, usually majority", "Reduced, sometimes minimal"],
      ["Line management", "Limited or coaching-based", "Extensive"],
      ["Directed time limit", "Applies (classroom teacher)", "Does not apply"],
      ["Guaranteed PPA", "Yes", "No statutory entitlement"],
      ["Pay ceiling", "£81,860", "£148,829"],
    ]},
    { kind: "callout", tone: "info", title: "The conditions difference is significant", text: "Lead practitioners remain classroom teachers for conditions of service purposes, so the 1,265-hour directed time limit and guaranteed PPA entitlement still apply. Leadership group members lose both. For many people this is the deciding factor." },

    { kind: "h2", text: "How schools set the range" },
    { kind: "p", text: "Governing bodies must set an individual range for each lead practitioner post within the national minimum and maximum, and must be able to justify the level. Factors that push a range higher include working across multiple schools or a whole trust, leading a priority improvement area, holding a specialism in a shortage subject, and formal responsibility for ECT or trainee development." },
    { kind: "p", text: "As with leadership posts, progression within the range depends on sustained high performance rather than annual increments, and you cannot progress beyond the top of your school's defined range without a re-evaluation of the post." },

    { kind: "h2", text: "Pension and take-home at lead practitioner level" },
    { kind: "p", text: "Lead practitioner salaries fall into the higher [Teachers' Pension](/teacher-pension/) contribution tiers, and the top of the range crosses into the 40% income tax band." },
    { kind: "table", caption: "Indicative deductions at lead practitioner salaries, rest of England 2026/27", head: ["Salary", "Pension tier", "Approx. monthly take-home"], rows: [
      ["£53,847 (minimum)", "9.6%", "£3,197"],
      ["£63,005", "10.2%", "£3,604"],
      ["£73,722", "11.7%", "£4,012"],
      ["£81,860 (maximum)", "11.7%", "£4,357"],
    ]},
    { kind: "p", text: "Crossing £72,534 moves you into the 11.7% pension tier, which noticeably flattens the net gain from progression at the top of the range. Model your exact position with the [teacher pay calculator](/teacher-pay-calculator/)." },

    { kind: "h2", text: "Applying for a lead practitioner post and negotiating the range" },
    { kind: "p", text: "Lead practitioner posts are advertised far less often than leadership vacancies, so how much you can earn depends heavily on finding the right vacancy. Trusts expanding CPD provision, National Centre for Excellence for Language Pedagogy-style partnerships and schools with strong initial teacher training intakes are the most common sources of well-funded posts. When you read an advert, the single most important number is the individual range the governing body has set, not the national maximum of £81,860." },
    { kind: "ul", items: [
      "**Ask where in the range the school expects to appoint.** Like leadership posts, schools often fund only the lower points in practice.",
      "**Evidence impact on other teachers' practice**, not just your own results — this is what distinguishes LP appointments from excellent classroom teachers.",
      "**Clarify the teaching commitment in writing**, because it determines whether the role genuinely leaves time for the development work you are paid for.",
      "**Check whether the post spans multiple schools.** Cross-trust briefs are the strongest justification for ranges towards the top of the spine.",
      "**Confirm conditions of service in the contract.** You should keep directed time limits and PPA entitlement as a lead practitioner.",
    ]},
    { kind: "callout", tone: "tip", title: "Compare against a TLR route before accepting", text: "A U3 teacher with a TLR 1 at £14,000 earns £66,835 — close to a mid-range lead practitioner. The LP post usually offers a higher ceiling and real development work, but check both packages through the [teacher pay calculator](/teacher-pay-calculator/) before deciding." },

    { kind: "h2", text: "Is lead practitioner a good career move?" },
    { kind: "p", text: "It suits teachers who are genuinely excellent in the classroom, enjoy developing colleagues, and do not want the accountability load of senior leadership. The pay ceiling is high enough that you are not financially penalised for staying out of management." },
    { kind: "p", text: "The main drawbacks are that posts are relatively scarce, the role is often less clearly defined than a leadership post, and in some schools it can become a catch-all for improvement work without the authority to deliver it. Ask hard questions about the brief and the range before accepting. Broader context on career routes is in the [UK teacher salary guide](/teacher-salary-uk/)." },
  ],
  faq: [
    { question: "What is the lead practitioner pay scale for 2026/27?", answer: "The national range is £53,847 to £81,860 in the rest of England and Wales, £55,331 to £83,346 in the London fringe, £58,119 to £86,136 in outer London, and £64,023 to £92,043 in inner London. Schools set an individual range within those boundaries." },
    { question: "What is a lead practitioner in a school?", answer: "A lead practitioner is a teacher whose main purpose is modelling and leading improvement in teaching across a school or group of schools. The role keeps a substantial teaching commitment and focuses on coaching, CPD and curriculum development rather than line management." },
    { question: "Is lead practitioner higher than UPS3?", answer: "Yes. The lead practitioner minimum of £53,847 is just above the U3 figure of £52,835, and the range extends to £81,860 — nearly £29,000 above the top of the upper pay range." },
    { question: "Is a lead practitioner part of the leadership team?", answer: "Not necessarily. Lead practitioners are paid on a separate range and remain classroom teachers for conditions of service purposes, keeping directed time protections and guaranteed PPA. Some schools include them in wider leadership meetings, but they are not part of the leadership group." },
    { question: "Do lead practitioners keep their PPA time?", answer: "Yes. Because they remain classroom teachers under the STPCD, lead practitioners keep guaranteed PPA time and the 1,265-hour directed time limit. Leadership group members lose both protections." },
    { question: "How much do lead practitioners earn compared with head of year roles?", answer: "A head of year typically earns U3 plus a TLR of roughly £3,650 to £8,912, giving around £56,500 to £61,750. Lead practitioners start above U3 at £53,847 and commonly reach the high £60,000s to low £70,000s, with top-of-range posts paying up to £81,860 in the rest of England." },
    { question: "What happened to Advanced Skills Teachers?", answer: "The Advanced Skills Teacher and Excellent Teacher schemes were abolished in 2013 and replaced by the single lead practitioner range. Teachers on the old scales were generally transitioned onto lead practitioner ranges or protected arrangements." },
    { question: "How does lead practitioner pay compare with an assistant head?", answer: "They overlap closely. A lead practitioner at around £66,392 is on a similar salary to an assistant head at L10 (£66,698). The lead practitioner keeps classroom teacher conditions; the assistant head takes on whole-school accountability with no directed time limit." },
  ],
  sources: SOURCES,
  updated: UPDATED,
};

const progressionPage: PageContent = {
  slug: "how-to-move-up-leadership-pay-scale",
  hub: "leadership",
  title: "How to Move Up the Leadership Pay Scale",
  metaTitle: "How to Move Up the Leadership Pay Scale — Progression Guide",
  metaDescription:
    "How leadership pay progression actually works: ISR mechanics, performance review evidence, pay committee decisions, and when to request a formal pay review.",
  primaryKeyword: "how do you move up the leadership pay scale",
  secondaryKeywords: [
    "leadership pay progression", "leadership pay review",
    "moving up leadership scale", "leadership pay appeal",
    "individual school range review", "leadership performance review pay",
    "how does leadership pay progression work",
    "leadership pay threshold", "leadership spine points explained",
  ],
  calculator: "none",
  intro:
    "Leadership pay progression is not automatic and it is not annual. You move within a seven-point individual school range on sustained high performance, and beyond it only if the range itself is re-evaluated. This guide explains both routes.",
  keyTakeaways: [
    "You can only progress within your individual school range — typically seven points — unless the range is formally reviewed.",
    "Progression requires sustained high performance against objectives, usually judged over two consecutive years.",
    "The pay committee, not your line manager, makes the decision, based on a recommendation.",
    "If you have reached the top of your ISR, the routes are a range review, a wider remit, or a new post.",
    "Governing bodies must review leadership pay annually, normally by 31 December.",
  ],
  blocks: [
    { kind: "h2", text: "The two ways leadership pay increases" },
    { kind: "p", text: "There are only two mechanisms, and confusing them wastes a lot of energy. The first is progression within your existing individual school range. The second is a change to the range itself. They involve different evidence, different decision-makers and different timescales." },
    { kind: "table", caption: "The two progression routes compared", head: ["Route", "What changes", "Evidence needed", "Typical gain"], rows: [
      ["Progression within ISR", "Your point on the spine", "Sustained high performance against objectives", "1–2 points"],
      ["ISR review", "The range attached to the post", "Change in size, complexity or remit of the job", "3–7 points"],
    ]},
    { kind: "p", text: "On top of both, the annual STPCD pay award lifts every spine point — 3.5% for 2026/27. That is not progression; it applies whether or not you move point. Details are on the [teacher pay rise page](/teacher-pay-rise/)." },

    { kind: "h2", text: "Progressing within your individual school range" },
    { kind: "p", text: "Your ISR is a seven-point slice of the [leadership spine](/leadership-pay-scale/). When you were appointed you started somewhere in it — often at the bottom, sometimes a point or two up if you negotiated well. Progression moves you towards the top." },
    { kind: "h3", text: "The performance standard" },
    { kind: "p", text: "The STPCD requires that leadership progression reflects sustained high quality of performance, judged against your objectives and the relevant standards. This is a materially higher bar than the classroom teacher standard, where progression is normally annual subject to satisfactory performance." },
    { kind: "p", text: "Most schools interpret sustained as meaning two consecutive successful review cycles. Some award a point annually where performance is consistently strong; others are considerably more restrictive. Your school's pay policy sets this out and you are entitled to see it." },
    { kind: "h3", text: "What actually counts as evidence" },
    { kind: "ul", items: [
      "**Outcomes against your specific objectives** — not the school's general performance, but the parts you own.",
      "**Impact data with a clear causal story** — attendance, behaviour, outcomes, staff retention in your area of responsibility.",
      "**Evidence of impact beyond your own remit** — leading trust-wide work, supporting another school, external recognition.",
      "**Development of others** — colleagues you have coached into promotion or improved practice.",
      "**Handling of a significant challenge** — an inspection, a restructure, a safeguarding case handled well.",
    ]},
    { kind: "callout", tone: "tip", title: "Build the evidence during the year, not at review", text: "Leadership objectives are usually broad and long-term, which makes them easy to under-evidence. Keep a running record with dates and data throughout the year. A one-page impact summary submitted with your review is far more persuasive than a conversation." },

    { kind: "h2", text: "Who actually decides" },
    { kind: "p", text: "Your reviewer makes a recommendation. The pay committee of the governing body makes the decision. This separation is deliberate and it matters when things go wrong — a supportive line manager cannot guarantee you a point, and an unsupportive one is not the final word." },
    { kind: "p", text: "For a headteacher, the review is conducted by a panel of governors, usually with an external adviser, and the recommendation goes to the pay committee in the same way." },
    { kind: "table", caption: "Who does what in the pay process", head: ["Stage", "Who", "Timing"], rows: [
      ["Objectives set", "Reviewer and postholder", "Autumn term"],
      ["Performance review meeting", "Reviewer (panel for heads)", "Autumn term"],
      ["Recommendation made", "Reviewer", "By 31 October for heads"],
      ["Pay decision", "Pay committee", "By 31 December for heads"],
      ["Decision confirmed in writing", "Governing body / trust", "Within 5 working days"],
      ["Appeal window", "Postholder", "Usually 10 working days"],
    ]},

    { kind: "h2", text: "When you have reached the top of your range" },
    { kind: "p", text: "This is the position most experienced leaders eventually reach, and the one most guides ignore. Once you are at the top point of your ISR, no amount of good performance will move you. The point itself is the cap." },
    { kind: "p", text: "There are three realistic options." },
    { kind: "ol", items: [
      "**Request a review of the ISR.** This only succeeds if the job has genuinely changed — the school has grown, you have taken on a second site or a trust-wide brief, or the structure has been reorganised around you.",
      "**Negotiate a formally expanded remit.** If you want a higher range, propose the additional responsibility that would justify it rather than asking for more money for the same job.",
      "**Move.** A post at a larger school, or a step up from assistant to [deputy](/deputy-head-teacher-salary/) or from deputy to [headteacher](/head-teacher-salary/), resets you onto a new and higher range.",
    ]},
    { kind: "callout", tone: "warn", title: "A range review is a review of the post, not of you", text: "Pay committees respond to evidence that the job has changed in size or complexity. Framing a request around your own performance or length of service is the most common reason these requests fail. Document what the post now requires that it did not before." },

    { kind: "h2", text: "Making a formal pay review request" },
    { kind: "p", text: "If you believe your range no longer reflects the post, put it in writing to the chair of the pay committee. A strong request generally contains a clear description of how the post has changed with dates, quantified evidence such as pupil numbers, staff managed or budget held, benchmarking against comparable posts in similar schools, reference to the relevant clauses of the school pay policy and the STPCD, and a specific proposed range rather than a vague request." },
    { kind: "p", text: "Time it to land before the pay committee meets, which for most schools means the autumn term. A request submitted in June will usually wait until December regardless of its merits." },

    { kind: "h2", text: "If the decision goes against you" },
    { kind: "p", text: "You are entitled to be told the decision in writing and to understand the reasons. Every school pay policy must include an appeals procedure, and the usual window is ten working days from written notification." },
    { kind: "p", text: "An appeal is normally heard by a different committee of governors. Bring your union representative — NAHT and ASCL both represent school leaders on pay matters and have seen far more of these cases than you have. Appeals succeed most often where the school has failed to follow its own policy, applied criteria inconsistently between postholders, or failed to give reasons." },

    { kind: "h2", text: "Common mistakes that block progression" },
    { kind: "ul", items: [
      "**Vague objectives.** If your objectives are not measurable, you cannot evidence meeting them.",
      "**Not reading the school pay policy.** It defines the criteria you will actually be judged against.",
      "**Confusing performance with post size.** Great performance moves you within the range; only a changed job changes the range.",
      "**Missing the timing.** Pay decisions cluster in the autumn term.",
      "**Accepting a verbal outcome.** Decisions must be confirmed in writing, and the appeal clock runs from that.",
      "**Not benchmarking.** Comparable ranges at similar local schools are legitimate and persuasive evidence.",
      "**Forgetting the pension effect.** Progression permanently increases your career average [pension](/teacher-pension/), so the long-term value exceeds the salary gain.",
    ]},

    { kind: "h2", text: "What progression is actually worth" },
    { kind: "p", text: "A single spine point is worth roughly 2.4% of salary. That is a useful benchmark when deciding whether to invest effort in a pay case." },
    { kind: "table", caption: "Value of one spine point, rest of England 2026/27", head: ["From", "To", "Gross gain", "Approx. net monthly gain"], rows: [
      ["L6 £60,514", "L7 £62,004", "£1,490", "£64"],
      ["L12 £70,022", "L13 £71,746", "£1,724", "£75"],
      ["L18 £81,024", "L19 £83,019", "£1,995", "£85"],
      ["L24 £93,754", "L25 £96,063", "£2,309", "£98"],
    ]},
    { kind: "p", text: "Each point also adds permanently to your pension, because the scheme is career average. A point gained at 45 continues paying into every subsequent year of accrual, which is why early progression is worth disproportionately more than late progression." },
  ],
  faq: [
    { question: "How do you move up the leadership pay scale?", answer: "There are two routes. You progress within your seven-point individual school range by demonstrating sustained high performance against your objectives, usually over two consecutive review cycles. To go beyond your range, the range itself must be re-evaluated because the post has grown in size or complexity, or you must move to a new post." },
    { question: "Is leadership pay progression automatic each year?", answer: "No. Unlike the main pay range, where progression is normally annual subject to satisfactory performance, leadership progression requires sustained high quality performance. Many schools expect two consecutive successful years before awarding a point, and your school's pay policy sets the exact criteria." },
    { question: "Who decides leadership pay progression?", answer: "The pay committee of the governing body makes the decision, based on a recommendation from your reviewer. For headteachers the review is conducted by a governor panel, usually with an external adviser. The decision must be confirmed to you in writing." },
    { question: "What happens when you reach the top of your leadership range?", answer: "You cannot progress further on performance alone. Your options are to request a review of the individual school range on the basis that the post has changed, to negotiate a formally expanded remit that justifies a higher range, or to move to a post at a larger school." },
    { question: "How does leadership pay progression differ from main scale progression?", answer: "On the main pay range, movement is normally annual and automatic subject to satisfactory performance. On the leadership spine you progress within your ISR only where there is evidence of sustained high performance, most schools expect two consecutive successful years per point, and you cannot exceed the top of your ISR without the post itself being re-evaluated." },
    { question: "Can I appeal a leadership pay decision?", answer: "Yes. Every school pay policy must include an appeals procedure, normally with a ten working day window from written notification. Appeals are usually heard by a different governor committee and succeed most often where the school did not follow its own policy or gave no reasons." },
    { question: "How much is one leadership spine point worth?", answer: "Roughly 2.4% of salary. At L12 in the rest of England that is about £1,724 gross, worth around £75 a month after tax, National Insurance and pension. Each point also permanently increases your career average pension." },
    { question: "When are leadership pay decisions made?", answer: "Most schools make leadership pay decisions in the autumn term. For headteachers the STPCD expects the review to be completed by 31 October and the pay determination by 31 December. Submit any pay review request well before those dates." },
  ],
  sources: SOURCES,
  updated: UPDATED,
};

export const leadershipPages: PageContent[] = [
  leadershipPillar,
  headTeacherPage,
  deputyHeadPage,
  assistantHeadPage,
  leadPractitionerPage,
  progressionPage,
];
